added api key

diff --git a/.github/workflows/main_uxai.yml b/.github/workflows/main_uxai.yml
--- a/.github/workflows/main_uxai.yml
+++ b/.github/workflows/main_uxai.yml
@@ -7,26 +7,56 @@ on:
   workflow_dispatch:
 
 jobs:
-  build-and-deploy:
+  build:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
 
-      - name: Set up Node.js
+      - name: Set up Node.js version
         uses: actions/setup-node@v2
         with:
-          node-version: 'v20.9.0' # Adjust the Node.js version as needed
+          node-version: 'v20.9.0'
 
-      - name: Install dependencies and build
+      - name: Install dependencies, build, and test
         run: |
           npm install
           npm run build --if-present
+          # npm run test --passWithNoTests
 
-      - name: Deploy to Azure Web App
+      - name: Zip artifact for deployment
+        run: |
+          if ! zip -r release.zip ./*; then
+            echo "Failed to create release.zip"
+            exit 1
+          fi
+
+      - name: Upload artifact for deployment job
+        uses: actions/upload-artifact@v2
+        with:
+          name: node-app
+          path: release.zip
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
+    environment:
+      name: 'Production'
+      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
+    
+    steps:
+      - name: Download artifact from build job
+        uses: actions/download-artifact@v2
+        with:
+          name: node-app
+      
+      - name: Debug workspace contents
+        run: ls -R ${{ github.workspace }}
+
+      - name: 'Deploy to Azure Web App'
         uses: azure/webapps-deploy@v2
         with:
-          app-name: 'UXAI' # Replace with your Azure App name
-          slot-name: 'Production' # Replace with your desired slot name
-          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9D66BCE0B0874E2586CCCAD25AABAFCA }} # Add your Azure publish profile secret
-          package: . # You can adjust the path if needed
+          app-name: 'UXAI'
+          slot-name: 'Production'
+          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9D66BCE0B0874E2586CCCAD25AABAFCA }}
+          package: ${{ github.workspace }}/release.zip
